=== namm-standards/standards/schemas/POStatus_v2015.1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://namm.org/b2b/2015/schemas" targetNamespace="http://namm.org/b2b/2015/schemas" elementFormDefault="qualified">
  <xs:element name="NAMM_POStatus">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Id">
	<xs:simpleType>
		<xs:restriction base="xs:string">
		<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	</xs:element>
        <xs:element name="POStatusRequestId">
	<xs:simpleType>
		<xs:restriction base="xs:string">
		<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	</xs:element>
        <xs:element name="Timestamp" type="xs:dateTime" />
        <xs:element name="BuyerOrderId">
	<xs:simpleType>
		<xs:restriction base="xs:string">
		<xs:maxLength value="25"/>
		</xs:restriction>
	</xs:simpleType>
	</xs:element>
        <xs:element name="DateOrdered" type="xs:date" />
        <xs:element name="BuyerName" type="xs:string"/>
        <xs:element name="Supplier">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PartyId">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Name" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="35"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Address" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Attn" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address1" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address2" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address3" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="City" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="30"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="State" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="PostalCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="9"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Country" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="CountryCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
    
		<xs:element name="SoldTo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PartyId">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Name" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="35"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Address" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Attn" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address1" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address2" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address3" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="City" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="30"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="State" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="PostalCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="9"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Country" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="CountryCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

        <xs:element name="StatusCode" type="xs:string"/>
        <xs:element name="PaymentTerms">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="StatusCode" type="xs:string" />
              <xs:element name="StatusMessage" type="xs:string" />
              <xs:element name="TermsCode">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:maxLength value="15"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ShipmentTerms">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="StatusCode" type="xs:string" minOccurs="0"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="ShipTo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PartyId">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Name" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="35"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Address" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Attn" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address1" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address2" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address3" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="City" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="30"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="State" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="PostalCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="9"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Country" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="CountryCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
        <xs:element name="Items">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Item">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="POLineNbr" type="xs:integer" />
                    <xs:element name="SequenceNbr" type="xs:integer" />
                    <xs:element name="StatusCode" type="xs:string" />
                    <xs:element name="StatusMessage" type="xs:string" />
                    <xs:element name="Qty" type="xs:decimal" />
                    <xs:element name="OriginalOrderQty" type="xs:decimal" />
                    <xs:element name="QtyUOM" type="xs:string" />
                    <xs:element name="UCValue" type="xs:decimal" />
                    <xs:element name="OriginalOrderUCValue" type="xs:decimal" />
                    <xs:element name="UCCurrencyCode" type="xs:string" />
                    <xs:element name="EstimatedShipDate" type="xs:date" minOccurs="0"/>
                    <xs:element name="SupplierOrderId" type="xs:string" />
                    <xs:element name="BuyerItemId" type="xs:string" />
                    <xs:element name="SupplierItemId" type="xs:string" />
                    <xs:element name="BarCodeId" type="xs:string" />
                    <xs:element name="BarCodeType" type="xs:string" />

                  <xs:element name="ShipTo" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PartyId">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="50"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Name" minOccurs="0">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="35"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Address" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Attn" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address1" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address2" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Address3" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="35"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="City" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="30"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="State" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="PostalCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="9"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Country" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="50"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="CountryCode" minOccurs="0">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:maxLength value="2"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>


                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="version" type="xs:decimal" use="required" fixed="2015.1"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== namm-standards/standards/examples/POStatus_v2015.1.xml
<NAMM_POStatus xmlns="http://namm.org/b2b/2015/schemas" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="2015.1" xsi:schemaLocation="http://namm.org/b2b/2015/schemas POStatus_v2015.1.xsd">
  <Id>B78DD4DC-09EB-4D47-AD3C-FF2105399CDE</Id>
  <POStatusRequestId>8814043038988</POStatusRequestId>
  <Timestamp>2014-05-07T01:21:44.107</Timestamp>
  <BuyerOrderId>8814043038988</BuyerOrderId>
  <DateOrdered>2014-05-01</DateOrdered>
  <BuyerName />
  <Supplier>
    <PartyId>0670716000009</PartyId>
    <Name>Korg USA Inc.</Name>
    <Address>
      <Attn />
      <Address1>316 S SERVICE RD</Address1>
      <Address2 />
      <Address3 />
      <City>MELVILLE</City>
      <State>NY</State>
      <PostalCode>117473228</PostalCode>
      <Country>USA</Country>
      <CountryCode>US</CountryCode>
    </Address>
  </Supplier>
  <SoldTo>
    <PartyId>698765768754</PartyId>
    <Name>Bill's Music</Name>
    <Address>
      <Attn>Accounts Payable</Attn>
      <Address1>1 FLUSHING AVE</Address1>
      <Address2></Address2>
      <Address3 />
      <City>BROOKLYN</City>
      <State>NY</State>
      <PostalCode>11205</PostalCode>
      <Country>USA</Country>
      <CountryCode>US</CountryCode>
    </Address>
  </SoldTo>
  <StatusCode />
  <PaymentTerms>
    <StatusCode>0</StatusCode>
    <StatusMessage />
    <TermsCode />
  </PaymentTerms>
  <ShipmentTerms>
    <StatusCode>0</StatusCode>
  </ShipmentTerms>
  <ShipTo>
    <PartyId>NAVY</PartyId>
    <Name>Bill's Music</Name>
    <Address>
      <Attn />
      <Address1>1 FLUSHING AVE</Address1>
      <Address2></Address2>
      <Address3 />
      <City>BROOKLYN</City>
      <State>NY</State>
      <PostalCode>11205</PostalCode>
      <Country>USA</Country>
      <CountryCode>US</CountryCode>
    </Address>
  </ShipTo>
  <Items>
    <Item>
      <POLineNbr>1</POLineNbr>
      <SequenceNbr>1</SequenceNbr>
      <StatusCode>Changes</StatusCode>
      <StatusMessage />
      <Qty>1</Qty>
      <OriginalOrderQty>1</OriginalOrderQty>
      <QtyUOM>EA</QtyUOM>
      <UCValue>47.00</UCValue>
      <OriginalOrderUCValue>30.75</OriginalOrderUCValue>
      <UCCurrencyCode>USD</UCCurrencyCode>
      <EstimatedShipDate>2014-05-07</EstimatedShipDate>
      <SupplierOrderId>OM99574453</SupplierOrderId>
      <BuyerItemId>KXXFKM2</BuyerItemId>
      <SupplierItemId>XFKM2</SupplierItemId>
      <BarCodeId />
      <BarCodeType>PartNumber</BarCodeType>
  <ShipTo>
    <PartyId>NAVY</PartyId>
    <Name>Bill's Music</Name>
    <Address>
      <Attn />
      <Address1>1 FLUSHING AVE</Address1>
      <Address2></Address2>
      <Address3 />
      <City>BROOKLYN</City>
      <State>NY</State>
      <PostalCode>11205</PostalCode>
      <Country>USA</Country>
      <CountryCode>US</CountryCode>
    </Address>
  </ShipTo>
    </Item>
    <Item>
      <POLineNbr>2</POLineNbr>
      <SequenceNbr>1</SequenceNbr>
      <StatusCode>Changes</StatusCode>
      <StatusMessage />
      <Qty>2</Qty>
      <OriginalOrderQty>6</OriginalOrderQty>
      <QtyUOM>EA</QtyUOM>
      <UCValue>16.80</UCValue>
      <OriginalOrderUCValue>16.80</OriginalOrderUCValue>
      <UCCurrencyCode>USD</UCCurrencyCode>
      <EstimatedShipDate>2014-06-12</EstimatedShipDate>
      <SupplierOrderId>OM99574453</SupplierOrderId>
      <BuyerItemId>KXGA1</BuyerItemId>
      <SupplierItemId>GA1</SupplierItemId>
      <BarCodeId>4959112069329</BarCodeId>
      <BarCodeType>GTIN-13</BarCodeType>
    </Item>
    <Item>
      <POLineNbr>2</POLineNbr>
      <SequenceNbr>2</SequenceNbr>
      <StatusCode>Changes</StatusCode>
      <StatusMessage />
      <Qty>4</Qty>
      <OriginalOrderQty>6</OriginalOrderQty>
      <QtyUOM>EA</QtyUOM>
      <UCValue>16.80</UCValue>
      <OriginalOrderUCValue>16.80</OriginalOrderUCValue>
      <UCCurrencyCode>USD</UCCurrencyCode>
      <SupplierOrderId>OM99574453</SupplierOrderId>
      <BuyerItemId>KXGA1</BuyerItemId>
      <SupplierItemId>GA1</SupplierItemId>
      <BarCodeId>4959112069329</BarCodeId>
      <BarCodeType>GTIN-13</BarCodeType>

    </Item>
  </Items>
</NAMM_POStatus>
